[build]
publish = "public"
command = "./stackbit-build.sh"

[build.environment]
HUGO_VERSION = "0.63.2"

[[plugins]]
package = "netlify-plugin-rss"
  [plugins.inputs]
  # required configs, customize as needed
  dirToScan = "/posts" # a subfolder to scan. "/" to scan all
  authorName = "Guy James"
  site_url = "https://guyjames.com"
  title = "Guy James RSS Feed"
  rssDescription = "RSS Feed description"
  categories = ['music']
