[build]
publish = "public"
command = "./stackbit-build.sh"

[build.environment]
HUGO_VERSION = "0.63.2"

[[plugins]]
package = "netlify-plugin-rss"
  [plugins.inputs]
  # required configs, customize as needed
  dirToScan = "/" # a subfolder to scan. "/" to scan all
  authorName = "Guy James"
  site_url = "https://guyjames.com"
  title = "Guy James RSS Feed"
  rssDescription = "Idle speculations you are doing well to ignore"
  categories = ['GameB', 'P2P', 'collapse', 'regenerative cultures', 'psychedelics', 'music']

  # # optional configs, defaults shown
  # rssFaviconUrl = "https://swyx.io/favicon.png"
  # docs = "http://example.com/rss/docs.html"
  # managingEditor = "authorName"
  # webMaster = "authorName"
  # copyright = "2020 ${authorName}"
  language = "en-GB"
  pubDate = "new Date().toUTCString(),"
  # ttl = "60" # aka refresh every hour

  # # cheerio selectors for extractMetadataFromFile
  # # defaults shown
  # contentSelector = "main"
  # publishDateSelector = # if not specified, we use the date of file creation
  # descriptionSelector = "meta[name=description]" # probably no need to change
  # titleSelector = "title" # probably no need to change

  # # developer configs
  # debugMode = false # (for development) turn true for extra diagnostic logging
